name: Sync Script 2

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  sched-job-0:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: |
          npm install
          node main.js
      - name: Download
        run: | 
          rm -f gg.js
          wget https://ltn.hitomi.la/gg.js --header "referer: https://hitomi.la/"
          python3 sync.py
      - name: A
        run: |
          git config --local user.email "violet.dev.master@gmail.com"
          git config --local user.name "violet-dev"
          git config --global pull.rebase false
          git add gg.js
          git add hitomi_get_image_list_v3.js
          git commit -m "update gg"
          git pull
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          branch: 'main'
          github_token: $ 
